name: caller_kcocuk
on:
  schedule:
    # At 03:00 on Monday, Wednesday, and Friday..
    - cron:  '0 3 * * 1,3,5'

env:
  WEBSITE: biraradamoda
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GENDER: kcocuk
jobs:
  defacto_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: defacto
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: kcocuk
    secrets: inherit
  koton_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: koton
      maxconcurrency: '1'
      WEBSITE: biraradamoda
      GENDER: kcocuk
    secrets: inherit
  lcwaikiki_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: lcwaikiki
      WEBSITE: biraradamoda
      GENDER: kcocuk
      maxconcurrency: '10'
    secrets: inherit
  beymen_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: beymen
      WEBSITE: biraradamoda
      GENDER: kcocuk
      maxconcurrency: '5'
    secrets: inherit
  hm_job:
    uses: ./.github/workflows/reusable.yml
    with:
      marka: hm
      WEBSITE: biraradamoda
      GENDER: kcocuk
      maxconcurrency: '1'
    secrets: inherit