name: kadin-merge-aggr
on:
   workflow_dispatch:
env:
  WEBSITE: biraradamoda
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  GENDER: kadin
jobs:
  merge_change_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: kadin
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: 'npm install'
      - name: Decript data
        run: 'npm run decryptData'
      - name: Download data
        run: 'node utils/downloadData.js'       
      - name: generate keywords
        id: generatekeywords
        run: node utils/generateKeywords.js
      - name: relocatedata
        id: relocateData
        run: node utils/relocateData.js
      - name: merge files
        id: mergefiles
        run: node utils/mergefiles.js
      - name: generate navigation
        id: generatenavigation
        run: node utils/genNav/NavGenRunner.js
      # - name: generate agregation report
        # id: genagrep
        # run: node utils/report/generateAggregationReport.js
      - name: build
        id: build
        run: npm run build
      - name: Commit report
        run: |
          git config --global user.name 'Serdar Ashirov'
          git config --global user.email 'webapis@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "Automated report."
          git push